### ISSUE TITLE
Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by exiled-serenity** [gwpmad/automate-tweetdeck#1]
I'm getting this error when I try to use your program, I think there's something wrong with the element handle that pulls the chromium window into focus but I have no idea what that could be.
```
Error: TypeError: Cannot read property 'focus' of null
    at focusAndType (C:\Users\[Censored Name]\Google Drive\Projects\gpt2\automate-tweetdeck-master\index.js:18:23)
    at logIn (C:\Users\[Censored Name]\Google Drive\Projects\gpt2\automate-tweetdeck-master\index.js:31:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\[Censored Name]\Google Drive\Projects\gpt2\automate-tweetdeck-master\index.js:115:5
```
Because of this it just opens the window and then doesn't control anything.

**Comment by gwpmad** [comment]
Hi @lflad sorry it doesn't work. There's a good chance this project is out of date now (and it was always somewhat buggy) but I'll fire it up again and see if I get the same error as you.

I was trying to solve a problem that I'm not sure was all that solvable. I'll update the readme to reflect that

**Comment by exiled-serenity** [comment]
Have you had any luck with this?

**Comment by gwpmad** [comment]
Right so I had a look and I get the same problem as you. The issue appears to be that the username and password fields (when logging into Tweetdeck) have changed. They used to have the class names [specified here](https://github.com/gwpmad/automate-tweetdeck/blob/master/index.js#L29-L30) but now those lines of code are returning `null` because the class names have changed for whatever reason. I think Twitter has redone the login page. The script tells Chromium to `focus()` on the fields in order to type but it can't focus on `null`.

I've screenshotted the username element in Chrome Dev Tools for clarity (the password element is below it)
![image](https://user-images.githubusercontent.com/14062617/76450897-7b358180-63c6-11ea-93bd-5467f31c2a98.png)

This is a buggy program at the best of times and to be honest I don't have a lot of time to fix it at the moment. If you fancy having a go at it yourself and submitting a pull request I'd welcome that. Thanks
